### ISSUE TITLE
sceneView view doesn't open / appear.

### ISSUE THREAD

**Issue by jasonkneen** [hansemannn/titanium-arkit#1]
Tried this in an Alloy Project -- brand new project. 6.2.0.GA -- installed to iOS11 on an iPhone 7.

```javascript
var ARKit = require('ti.arkit');

var sceneView = ARKit.createSceneView({
  scene: 'Titanium.scnassets/ti-logo.scn' // Create your Scene Assets in Xcode and place them in app/platform/ios (Alloy) or platform/ios (Classic)
});


$.index.addEventListener('open', function() {
console.log("OPENED")
  sceneView.run();
});
```
$.index.add(sceneView);
$.index.open();```

Permissions are all set in TiApp.xml.

App loads with black screen (the index.xml) -- nothing else happens. "OPENED" appears in the console, no other errors that indicate an issue.

**Comment by hansemannn** [comment]
Hups, it has to be in Resources/ (classic) or app/assets/iphone (Alloy), so it gets copied to the built app-bundle. The `platform` one is for platform-specific assets that are actually compiled (like storyboards). Will update the readme, can you validate again?

**Comment by jasonkneen** [comment]
works -- thanks! -- just need comment updated in code.

**Comment by hansemannn** [comment]
Updated already :-) Thanks Jason!

**Comment by kilyan-s** [comment]
Hello,

When I launch the app, I have a black screen and then the app crash. 
I put Titanium.scnassets/ti-logo.scn in the root Ressources folder. 

Thanks for your help,
