### ISSUE TITLE
missing libtitanium-arkit-master.a

### ISSUE THREAD

**Issue by alexyellowcube** [hansemannn/titanium-arkit#4]
i try to use your module, but i get error message as show as below:

[ERROR] :  Module titanium-arkit-master version 1.0.0 is missing library file: /Users/dinghengduan/Documents/Appcelerator_Studio_Workspace/test arkit/modules/iphone/titanium-arkit-master/1.0.0/libtitanium-arkit-master.a

Is there a file missing in your module?

**Comment by hansemannn** [comment]
Please ensure to properly include the module, there is no reference to any file called `libtitanium-arkit-master.a` in the official release from the `Releases` tab.

**Comment by alexyellowcube** [comment]
Thanks you for your fast respond. i had solve it by download from the releases tab and it work well.

wish to have the object recognition for this module in the future.
